FROM ubuntu:18.04
RUN apt update && apt upgrade -y
RUN apt install python3-dev python3-setuptools python3-pip -y
RUN apt install libev-dev -y
ENV LANG=C.UTF-8
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code
RUN pip3 install pipenv
ADD . /code/
RUN pipenv install