version: '3'

services:

  nginx:
    image: nginx:1.14
    restart: always
    container_name: prod_nginx
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ../storage/cert/conf:/etc/letsencrypt
      - ../storage/cert/www:/var/www/certbot
      - ../storage/nginx:/etc/nginx/conf.d
      - .:/code
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - web-daphne
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 168h & wait $${!}; done;'"
    volumes:
      - ../storage/cert/conf:/etc/letsencrypt
      - ../storage/cert/www:/var/www/certbot

  rabbit:
    image: rabbitmq:3.7.8-management
    restart: always
    env_file:
      - .env
    volumes:
      - ../storage/rabbit:/var/lib/rabbitmq
      - ../storage/rabbit/logs:/var/logs/rabbitmq

  web-celery:
    build:
      context: .
      dockerfile: Dockerfile.bjoern
    volumes:
      - .:/code
    command: bash -c "pipenv run celery -A mysite worker -l info -f logs/celery.logs"
    depends_on:
      - rabbit
    links:
      - rabbit

  db:
    image: postgres:9.5
    volumes:
      - ../storage/postgres:/var/lib/postgresql/data
      - ../storage/for_dump:/dump
    restart: always
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    volumes:
      - ../storage/redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.bjoern
    restart: always
    command: pipenv run python run_web_bjoern.py
    env_file:
      - .env
    links:
      - db
      - redis
      - rabbit
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbit
      - redis
      - web-daphne

  web-daphne:
    build:
      context: .
      dockerfile: Dockerfile.bjoern
    volumes:
      - .:/code
    command: bash -c "pipenv run python manage.py collectstatic --no-input && pipenv run python manage.py migrate && pipenv run daphne mysite.asgi:application -p 9000 -b 0.0.0.0"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
