version: '3'

services:

  nginx:
    image: nginx:1.14
    restart: always
    container_name: prod_nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/:/etc/nginx/
      - /var/www/:/var/www/
      - .:/code
    ports:
      - 80:80
      - 443:443
    links:
      - web
    depends_on:
      - web

  db:
    image: postgres:9.5
    volumes:
      - ../storage/mysite/postgres:/var/lib/postgresql/data
      - ../storage/mysite/for_dump:/dump
    restart: always
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    volumes:
      - ../storage/mysite/redis:/data

  web:
    build: .
    restart: always
    command: pipenv run daphne mysite.asgi:application -p 8000 -b 0.0.0.0
    links:
      - db
      - redis
    volumes:
      - .:/code
    depends_on:
      - db
      - redis