version: '3'

services:

  nginx:
    image: nginx:1.14
    restart: always
    container_name: prod_nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/:/etc/nginx/
      - /var/www/:/var/www/
      - .:/code
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - web-daphne
    depends_on:
      - web

  db:
    image: postgres:9.5
    volumes:
      - ../storage/mysite/postgres:/var/lib/postgresql/data
      - ../storage/mysite/for_dump:/dump
    restart: always
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    volumes:
      - ../storage/mysite/redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.bjoern
    restart: always
    command: pipenv run python -c "from mysite.wsgi import application; import bjoern; bjoern.run(application, '0.0.0.0', 8000)"
    links:
      - db
      - redis
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web-daphne

  web-daphne:
    build: .
    volumes:
      - .:/code
    command: bash -c "pipenv run python manage.py collectstatic --no-input && pipenv run python manage.py migrate && pipenv run daphne mysite.asgi:application -p 9000 -b 0.0.0.0"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis