# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('date_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
