# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20170322_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='refer',
            field=models.SlugField(default='not_refer', null=True),
        ),
    ]
