# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20170112_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='note.Note'),
        ),
    ]
