# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20170120_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
