# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20170126_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rubric',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
