# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_note_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rubric',
            field=models.CharField(default='Other', max_length=255),
        ),
    ]
