# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20170129_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=7)),
                ('path', models.TextField(max_length=255, verbose_name='Path')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(max_length=3, verbose_name='Status code')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
