# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_something'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='something',
            name='status_code',
            field=models.IntegerField(verbose_name='Status code'),
        ),
    ]
