# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0018_auto_20170308_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='something',
            name='refer',
            field=models.CharField(default='not_refer', max_length=255),
        ),
    ]
