# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0020_auto_20170313_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='refer',
            field=models.CharField(blank=True, default='not_refer', max_length=255),
        ),
    ]
