# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0021_auto_20170313_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='something',
            name='refer',
            field=models.CharField(default='not_refer', max_length=255, null=True),
        ),
    ]
