# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_fuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='fuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
