# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_auto_20170123_1152'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visitor',
            managers=[
            ],
        ),
    ]
