# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 11:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_auto_20170123_1152'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visitor',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
