# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0009_auto_20170123_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='provider',
        ),
    ]
