# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_remove_visitor_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
