# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_auto_20170123_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='access_token',
            field=models.SlugField(default=None, max_length=255),
        ),
    ]
