# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0014_visitor_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='access_token',
            field=models.SlugField(max_length=255),
        ),
    ]
