# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_auto_20170123_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='access_token',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='image_url',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
