# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0016_auto_20170123_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='link',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='timezone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
