# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_auto_20170124_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='link',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='timezone',
        ),
    ]
