# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0018_auto_20170124_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
